version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./firebase.json:/app/firebase.json
    # depends_on:
    #   - db

  # db:
  #   image: postgres:16
  #   container_name: postgres-db
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: adminpassword
  #     POSTGRES_DB: ethical_hacking_db
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
