name: Testing Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests on Testing Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Backend Tests
        run: |
          cd backend
          pytest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm run test

      - name: Push Code to Testing Branch
        if: success()
        run: |
          git fetch origin
          git checkout testing
          git merge --no-ff main -m "Auto-merge from main after successful tests"
          git push origin testing
