name: Staging Deployment (Auto Railway Deployment on completion)

on:
  workflow_run:
    workflows: ["Testing Pipeline"]
    types:
      - completed

jobs:
  merge-to-staging:
    name: Merge Testing into Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/Harrysibbenga/EthicalHackingPlatform.git

      - name: Merge Testing into Staging
        run: |
          git fetch origin
          git checkout staging || git checkout -b staging origin/staging
          git merge --no-ff origin/testing -m "Auto-merge from testing after successful tests"
          git push origin staging