name: Run Tests & Merge to Testing

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Tests on Main Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "Running Tests..."
          # Replace this with actual test commands, e.g., pytest
          pytest tests/

  merge-to-testing:
    name: Merge Main into Testing
    runs-on: ubuntu-latest
    needs: run-tests
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/Harrysibbenga/EthicalHackingPlatform.git

      - name: Merge Main into Testing
        run: |
          git fetch origin
          git checkout testing || git checkout -b testing origin/testing
          git merge --no-ff main -m "Auto-merge from main after successful tests"
          git push origin testing
